### ISSUE TITLE
Remove code duplication

### ISSUE THREAD

**Issue by humphd** [trangntt-016/static-site-generator#4]
https://github.com/trangntt-016/static-site-generator/blob/main/src/main/java/com/os/jssg/utils/HTMLUtils.java#L24-L34 and https://github.com/trangntt-016/static-site-generator/blob/main/src/main/java/com/os/jssg/utils/FileUtils.java#L62-L93 are very similar, and one of these should be removed.  I'd suggest leaving all HTML logic in the HTMLUtils.

**Comment by trangntt-016** [comment]
Thanks for your feedback, I've just merged FileUtils to HTMLUtils

**Comment by trangntt-016** [comment]
@humphd  do you mind checking if the codes are okay so that I can close this issue?

**Comment by humphd** [comment]
Way better!
