### ISSUE TITLE
Add support for config.json

### ISSUE THREAD

**Issue by Andrewnt219** [trangntt-016/static-site-generator#7]
## Describe the feature
Hi @trangntt-016, I want to add support for reading in a config.json as an alternative to CLI arguments (e.g. `--input`, `--lang`,...).
```
ssg --config ./ssg-config.json
```

```
{
  "input": "./docs",
  "output": "./web",
  "future-feature": "should be ignored for now"
}
```

## Describe the solution

For supporting `--config`, I'll add another `@CommandLine.Option`. If the `--config` flag is used, ignore other flags.

I'm going to init the value of JssgApplication with pairs from the JSON file. That way, all the logic for parsing the file can be the same. To parse the JSON config, I'll have to add `org.json` or `GSON` as a dependency.

**Comment by trangntt-016** [comment]
Okay, I'm assigning this to you @Andrewnt219 . Have fun and don't hesitate to ask any questions you may have!

**Comment by Andrewnt219** [comment]
I cannot run the project. Do I have to get the `jssg-0.0.1-SNAPSHOT.jar` from you?

**Comment by trangntt-016** [comment]
Yup, I removed .jar file from my repo but you can create another jar file in your repo.

To create jar file, try one of these:
- If you using Intelliji: View => Tool Windows => Click on the button `Toggle Skip Tests Mode` => clean => install
- If you already install Maven: From your current repo, ` mvn clean install -DskipTests`

To run the project:
- ./jssg-0.0.1-SNAPSHOT.jar -v

To run `jssg -v`, you have to change the filepath in .bat file which I mentioned in the README.md

**Comment by Andrewnt219** [comment]
Oh, so that's the equivalent of `npm install`. Got it running now. Thanks.
